spring:
  config:
    activate:
      on-profile: "production"
  application:
    name: "Confluent MCP Proxy"
  mvc:
    async:
      request-timeout: 60000
  main:
    web-application-type: reactive
mcp:
  server:
    name: "Confluent MCP Proxy"
    version: 1.0.0
    mode: "sse"
kafka:
  client-id: ${CLIENT_ID:#{null}}
  application-id: "mcp.proxy"
  broker-servers: ${BROKER_URL}
  jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${JAAS_USERNAME}" password="${JAAS_PASSWORD}";
  sr-url: ${SR_URL}
  sr-basic-auth: ${SR_API_KEY}:${SR_API_SECRET}
  registration-topic-name: ${REGISTRY_TOPIC:#{null}}
authentication:
  cache-size: 100
  cache-expiry-in-second: 300
  enabled: true
---
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: "Confluent MCP Proxy"
  mvc:
    async:
      request-timeout: 60000
  main:
    web-application-type: reactive
mcp:
  server:
    name: "Confluent MCP Proxy"
    version: 1.0.0
    mode: "sse"
kafka:
  client-id: ${CLIENT_ID:#{null}}
  application-id: "mcp.proxy"
  broker-servers: ${BROKER_URL}
  jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${JAAS_USERNAME}" password="${JAAS_PASSWORD}";
  sr-url: ${SR_URL}
  sr-basic-auth: ${SR_API_KEY}:${SR_API_SECRET}
  registration-topic-name: ${REGISTRY_TOPIC:#{null}}
authentication:
  cache-size: 100
  cache-expiry-in-second: 300
  enabled: false
---
spring:
  config:
    activate:
      on-profile: "stdio"
  application:
    name: "Confluent MCP Proxy"
  main:
    banner-mode: off
    web-application-type: none
mcp:
  server:
    name: "Confluent MCP Proxy"
    version: 1.0.0
    mode: "stdio"
kafka:
  client-id: ${CLIENT_ID:#{null}}
  application-id: "mcp.proxy"
  broker-servers: ${BROKER_URL}
  jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${JAAS_USERNAME}" password="${JAAS_PASSWORD}";
  sr-url: ${SR_URL}
  sr-basic-auth: ${SR_API_KEY}:${SR_API_SECRET}
  registration-topic-name: ${REGISTRY_TOPIC:#{null}}
logging:
  file:
    name: ${LOG_FILE}
  pattern:
    console: ""